### ISSUE TITLE
扩展管理插件新功能想法

### ISSUE THREAD

**Issue by HuangAdam** [zangse/vue-chrome-extension#10]
扩展管理插件的常用插件启动真的很是方便
可不可以尝试加入标签分类，即自己创建标签，如视频、科学上网等等，然后把扩展插件分类进这些标签中，当面对某些场景的时候可以一键开启所选标签的所有插件

可不可以加入右上角扩展插件图标隐藏功能（不确定能否实现）
像我这样的强迫症，看到一长条的的图标很是难受，可不可以隐藏起来，将隐藏起来的插件数量在左上角该插件图标右下角显示，被隐藏的插件-的图标上的数量提示以扩展管理插件图标变色的方式来展示，由蓝色到黑色，新弹出的被隐藏插件信息有声音提示

**Comment by HuangAdam** [comment]
可以手动隐藏，但不知道有没有api可以让扩展管理来接管这个呢，直接划一个类用来不显示图标的

**Comment by HuangAdam** [comment]
> 可以手动隐藏，但不知道有没有api可以让扩展管理来接管这个呢，直接划一个类用来不显示图标的

话说为啥我一个插件开启隐藏，然后用扩展管理关闭所有，再打开常用/所有，除扩展管理的其他插件全部变成隐藏

**Comment by zangse** [comment]
reply:
1.右上角的图标代表的是当前浏览器开启的扩展，这个是系统提供的，无法更改呢；
2.打开常用扩展，需要在第三页设置你的常用扩展，可以一键打开。
3.设置标签分类目前市场上有的插件实现了，在考虑是否跟进相关功能。由于时间的原因和缺乏UI，短时间内可能无法更新插件。
谢谢你的建议。：）
