### ISSUE TITLE
请求上架新版edge扩展商店

### ISSUE THREAD

**Issue by ChirmyRam** [zangse/vue-chrome-extension#12]
新版edge浏览器的扩展商店相对于Chrome商店更容易访问，请求在edge扩展商店上架。

**Comment by andy-sun-007** [comment]
> 新版edge浏览器的扩展商店相对于Chrome商店更容易访问，请求在edge扩展商店上架。

强烈支持，同样需要书签管理这个插件，请求上架新版edge浏览器的扩展商店！！！

**Comment by zangse** [comment]
> > 新版edge浏览器的扩展商店相对于Chrome商店更容易访问，请求在edge扩展商店上架。
> 
> 强烈支持，同样需要书签管理这个插件，请求上架新版edge浏览器的扩展商店！！！

打包了zip文件，您可以本地安装。
[release](https://github.com/zangse/vue-chrome-extension/releases/tag/0.0.1)
目前有计划重写这个扩展。
