### ISSUE TITLE
能不能实现书签管理页新建文件夹功能呢。。。

### ISSUE THREAD

**Issue by NathanIceSea** [zangse/vue-chrome-extension#2]
不知道 Chrome 有没有相关 API

**Comment by zangse** [comment]
有的，已经实现了，我只是每次移动的时候可以选择新建文件夹，没有在主界面做这个操作 ，你可以试着移动一个文件夹，然后选择新建文件夹@NathanIceSea

**Comment by zangse** [comment]
已经实现。官方也有相应API
