### ISSUE TITLE
扩展颜色

### ISSUE THREAD

**Issue by yu037991** [zangse/vue-chrome-extension#7]
没注意到已经启用的扩展是白色，未启用的是灰色，因为未启用的扩展的扩展图标依旧是原来的颜色，不太好辨别，建议把未启用的扩展的所有东西（包括扩展图标）都能蒙上一层灰色，比较好区分哪些扩展已经启用，顺便再提个建议，建议扩展管理的图标上面显示启用的扩展数量的功能有个开关，有的强迫症受不了图标上有数字

**Comment by zangse** [comment]
在系统的扩展栏里，浏览器右上角那一片，只会展示已启用的扩展图标，这个显示情况，第三方控件无法更改，扩展管理插件点击，弹出层里可以查看已开启扩展和关闭的扩展，还有可以设置常用扩展并一键开启或关闭扩展，扩展管理的下的数字小图标的数字展示的是当前浏览器已经开启的扩展数量，会在将来的版本中设置是否开启显示这个数字，谢谢您的反馈
